version: 2.1
jobs:
  run-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: python -m pip install -r requirements.txt
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Run Django Server
          command: python manage.py
      - run:
          name: Install netlify-cli
          command: npm install netlify-cli
      - run:
          name: Netlify Deploy
          command: npx netlify deploy --prod --dir=N_Creams --message="CircleCI Build $CIRCLE_BUILD_NUM" --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

workflows:
  run-test-workflow:
    jobs:
      - run-test
